import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "./components/theme"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

const inter = Inter({
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter} ${inter} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
