name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run at midnight every day
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v2
        with:
          repository: hungtran3011/MusikStreamingFE
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream repository
        run: git remote add upstream https://github.com/MusikStreaming/MusikStreamingFE.git 

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main  # Replace "main" with the appropriate branch name

      - name: Push changes
        run: git push origin main  # Replace "main" with the appropriate branch name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
